print("strip operations")
str = input("enter a string to perform the strip operations : ")
x = input("enter a character for left strip from above string : ")
y = input("enter a character for right strip from above string: ")
print("original stying : -->"+str)
print ("left strip on string : -->",str.lstrip(x))
print ("right strip on string : -->",str.rstrip(y))

s = input("enter a string to perform string split operations : \n")
print ("original string : --> ",s,"\n")
print(s.split(),"\n")
print("string spliting for specific time :")
a = int(input("enter a starting point for split the string :"))
print ("string split in ",a," part",s.split(' ' ,a ),"\n")
b = int(input("enter a starting point for split the string one more time :"))
print ("string split in ",b," part",s.split(' ' ,b ),"\n")
