import os
os.mkdir("james")
os.chdir("james")
# os.mkdir("bond")
a = os.getcwd()
print('a :  ', a)
os.mkdir("newdir")
os.chdir("newdir")
new = os.getcwd()
print('new : ', new)
os.rmdir("jhegf ecgkwugf dgfydgfgfm")