fi = open("testing.txt","r")
str = fi.read(10)
str1 = fi.read(2)
print( str)
print( str1)
position = fi.tell()
print('position : ', position)
str2 = fi.read(12)
print(str2)
position = fi.seek(0,0)
print('position : ', position)

test = open("taufik.txt", "r+")
i = input("write in a file named taufik.txt ")
test.write(i)

t1 = test.read(10)
print(t1)
t2 = test.tell()
print('current position : ', t2)
reset = test.seek(0,0)
print('new position :  ', reset)
test.close()
print("is file closed? ", test.closed)

